name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Install Deno
      uses: denoland/setup-deno@v2
      with:
        deno-version: v2.x

    - name: Test
      run: "deno task test"
